# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Net_Spider',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('create_by',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='\u521b\u5efa\u8005')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_by',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='\u66f4\u65b0\u8005')),
                ('update_date',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('remarks',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('del_flag',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='\u903b\u8f91\u6807\u8bb0')),
                ('spider_name',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='\u722c\u866b\u540d\u79f0')),
                ('net_project_id', models.UUIDField(default='', verbose_name='\u9879\u76eeid')),
                ('allowed_domains',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='\u57df\u540d')),
                ('proxy', models.BooleanField(default=False, verbose_name='\u4ee3\u7406')),
                ('keywords', models.TextField(blank=True, default='', verbose_name='\u5173\u952e\u8bcd\u63d2\u5165')),
                ('start_urls', models.TextField(default='', verbose_name='\u5165\u53e3\u8fde\u63a5')),
                ('spider_type', models.CharField(default='', max_length=50, verbose_name='\u722c\u866b\u7c7b\u578b')),
                ('rules', models.CharField(default='', max_length=255, verbose_name='\u89c4\u5219\u5165\u53e3')),
                ('fields', models.TextField(default='', verbose_name='\u5185\u5bb9\u89e3\u6790')),
                ('chinesename',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='\u7f51\u7ad9\u540d\u79f0')),
                ('area_id',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='\u5730\u57df\u7f16\u7801')),
                ('tablename', models.CharField(blank=True, default='', max_length=100, verbose_name='\u8868\u660e')),
                ('gen_gendbtable_id',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='\u5173\u8054\u8868id')),
                ('projectname',
                 models.CharField(blank=True, default='', max_length=100, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('keyword_type', models.CharField(blank=True, default='', max_length=100,
                                                  verbose_name='\u5173\u952e\u5b57\u903b\u8f91')),
            ],
        ),
    ]
